version: "3.9"

services:
  webhook:
    build: .
    container_name: webhook_app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=<your-server-ip>,localhost
    restart: always
