FROM python:3.12-slim


#install essential dependencies and clean up cahe 
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     build-essential \
#     libpq-dev \
#     && rm -rf /var/lib/apt/lists/*


RUN useradd -m appuser

WORKDIR /app

COPY requirements.txt .


RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt


COPY . .

# # Change ownership to non-root user
RUN chown -R appuser:appuser /app

# # Switch to non-root user
USER appuser

ENV PYTHONUNBUFFERED=1

EXPOSE 8000


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

